### ISSUE TITLE
Branching 'Arousal' in to emotional/physical

### ISSUE THREAD

**Issue by KateBlackThorn** [CognitiveAtlas/ontology#3]
We mentioned discussed dividing the current concept of Arousal into two branches: arousal (emotional), meaning general emotional intensity (I tend to feel emotions more intensely than others) and arousal (physical), meaning energetic responses (I feel jittery, I often feel restless). Our clinical team agreed this should be done.

**Comment by poldrack** [comment]
agree. this has been forked.
