### ISSUE TITLE
Recommended changes/additions to relationships between existing concepts

### ISSUE THREAD

**Issue by KateBlackThorn** [CognitiveAtlas/ontology#5]
Openness: This is one of the Big Five personality factors. These, by definition, are each a broad dimension composed of a set of correlated symptoms that map to primary concepts. the Openness personality factor is composed of the primary characteristics of curiosity, imagination, unfocussed, among others.  In the Atlas ‘imaginative, open, curious’ are listed as synonyms. However, these should be ‘part of’ Openness, not synonyms. Specifically,  the CA concepts curiosity and imagination, should be ‘part’ of Openness. Note that there are possibly other concepts that would be ‘part of’ the Openness personality factor,  but I did not do exhaustive search. May also be worth discussing if such broad dimensions should be listed as ‘concepts’.

Hyperactivity: Remove non-compliance as a synonym. Non-compliance should not be considered synonymous iwth hyperactivity. Hyperactivity may be a base cause of non-compliance, but cannot be considered the same phenotype. 

Social Phobia: Embarrassment should not be listed as a synonym of Social Phobia. Rather ‘embarrassment’ should be added as either a synonym for a ‘part of’ Shame.
Also, it is requested that ‘Social anxiety’ be listed as synonym for ‘Social Phobia’. A note from our clinical team: Social phobia is an ‘old term’ for ‘Social anxiety’, which is more widely used these days. So, may even consider changing to the primary concept to ‘Social anxiety’ with ‘social phobia’ as a listed synonym.

**Comment by poldrack** [comment]
one suggestion: please submit each recommended change as a separate issue, that way we can close them as we fix them.  I am going to create three new issues for this and then close this one.

**Comment by KateBlackThorn** [comment]
Yep, will do!
